import { invoke } from "@tauri-apps/api/core";
import type {
  AllPlantsRow,
  CatalogEntry,
  EventView,
  Location,
  NewPlant,
  PlantProfile,
  Settings,
  Space,
  WeatherSummary,
} from "./types";

export const api = {
  listDueToday: () => invoke<EventView[]>("list_due_today"),
  listSoon: () => invoke<EventView[]>("list_soon"),
  listAllPlants: () => invoke<AllPlantsRow[]>("list_all_plants"),
  markDone: (eventId: string) => invoke<void>("mark_done", { eventId }),
  snooze: (eventId: string, days: number) => invoke<void>("snooze", { eventId, days }),
  skipSoilWet: (eventId: string) => invoke<void>("skip_soil_wet", { eventId }),
  getPlant: (plantId: string) => invoke<PlantProfile>("get_plant", { plantId }),
  addPlant: (plant: NewPlant) => invoke<PlantProfile>("add_plant", { plant }),
  updatePlant: (plant: PlantProfile) => invoke<void>("update_plant", { plant }),
  deletePlant: (plantId: string) => invoke<void>("delete_plant", { plantId }),
  searchCatalog: (query: string, limit?: number) =>
    invoke<CatalogEntry[]>("search_catalog", { query, limit }),
  listSpaces: () => invoke<Space[]>("list_spaces"),
  addSpace: (name: string) => invoke<Space>("add_space", { name }),
  renameSpace: (spaceId: string, name: string) => invoke<void>("rename_space", { spaceId, name }),
  deleteSpace: (spaceId: string) => invoke<void>("delete_space", { spaceId }),
  getSettings: () => invoke<Settings>("get_settings"),
  updateSettings: (settings: Settings) => invoke<void>("update_settings", { settings }),
  searchPlaces: (query: string) => invoke<Location[]>("search_places", { query }),
  detectLocation: () => invoke<Location>("detect_location"),
  refreshWeather: (force = false) => invoke<boolean>("refresh_weather", { force }),
  getWeather: () => invoke<WeatherSummary | null>("get_weather"),
  isAutostartEnabled: () => invoke<boolean>("is_autostart_enabled"),
  setPinnedOnTop: (pinned: boolean) => invoke<void>("set_pinned_on_top", { pinned }),
  setActiveSpace: (spaceId: string | null) => invoke<void>("set_active_space", { spaceId }),
};
